### ISSUE TITLE
ImportError: No module named distutils

### ISSUE THREAD

**Issue by HeartUnchange** [alecthomas/SublimePythonImportMagic#2]
When I start SublimeText 2 ,the plugin does not work.I see the console printed "ImportError: No module named distutils" after "Reloading plugin C:\Users\ZHX\AppData\Roaming\Sublime Text 2\Packages\Python Import Magic\sublime_import_magic.py".How to fix it?Thanks.

**Comment by alecthomas** [comment]
This should be fixed now, but requires ST3.
